name: Daily Tech News Push

on:
  schedule:
    # 每天 UTC 时间 00:00 触发（即北京时间 08:00）
    - cron: '0 0 * * *'
  # 允许手动触发测试
  workflow_dispatch:

jobs:
  fetch-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install feedparser requests

      - name: Run news fetcher and send via ServerChan
        env:
          SERVERCHAN_SENDKEY: ${{ secrets.SERVERCHAN_SENDKEY }}
        run: |
          python .github/scripts/fetch_tech_news.py